apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
    name: json-to-avro-replicator
spec:
    kafkaConnect:
        version: 3.6.0
        replicas: 1
        config:
            connector.plugins:
                - org.apache.kafka.connect.json:json-source
                - org.apache.kafka.connect.avro:avro-converter
                - io.confluent.connect.replicator.ReplicatorSourceConnector
    tasks:
        - class: org.apache.kafka.connect.json.JsonSourceConnector
          config:
              topics: gold-json

        - class: org.apache.kafka.connect.avro.AvroConverter
          config:
              schemas.enable: true
              schema.registry.url: http://localhost:8081

    sourceConnector:
        class: io.confluent.connect.replicator.ReplicatorSourceConnector
        config:
            source.cluster.bootstrap.servers: localhost:9092
            destination.cluster.bootstrap.servers: localhost:9092
            topics: gold-avro

    sinkConnector:
        class: org.apache.kafka.connect.avro.AvroSinkConnector
        config:
            topics: gold-avro
