# To Spark to load main file from S3
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
    name: data-connection
spec:
    host: minio
    port: 9000
    accessStyle: Path
    credentials:
        secretClass: s3-credentials-class
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: s3-credentials-class
spec:
    backend:
        k8sSearch:
            searchNamespace:
                pod: {}
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    labels:
        secrets.stackable.tech/class: s3-credentials-class
data:
    # Base64 encoded MinIO username and password ("admin", "password")
    accessKey: YWRtaW4=
    secretKey: cGFzc3dvcmQ=
#
#
# To Spark to save logs to S3
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Bucket
metadata:
    name: spark-history
spec:
    bucketName: spark-logs
    connection:
        reference: history-connection
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
    name: history-connection
spec:
    host: minio
    port: 9000
    accessStyle: Path
    credentials:
        secretClass: history-credentials-class
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: history-credentials-class
spec:
    backend:
        k8sSearch:
            searchNamespace:
                pod: {}
---
apiVersion: v1
kind: Secret
metadata:
    name: history-credentials
    labels:
        secrets.stackable.tech/class: history-credentials-class
data:
    # Base64 encoded MinIO username and password ("admin", "password")
    accessKey: YWRtaW4=
    secretKey: cGFzc3dvcmQ=
