apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
    name: kafka-connect-source-connector
    labels:
        strimzi.io/cluster: kafka-connect-cluster
spec:
    class: org.apache.kafka.connect.file.FileStreamSourceConnector
    tasksMax: 1
    config:
        file: "/opt/kafka/LICENSE"
        topic: testtest
