apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
data:
  connect-config.json: |
    { "name": "my-connect", "config": { "connector.class": "io.confluent.connect.http.HttpSinkConnector", "tasks.max": "1", "topics": "tweet-json", "http.api.url": "http://localhost:57693/, "bootstrap.servers": "kafka-cluster-kafka-bootstrap:9092, localhost:9092, localhost:9093" } }
