apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
    name: hdfs
spec:
    image:
        productVersion: 3.3.4
        stackableVersion: 23.7.0
    clusterConfig:
        zookeeperConfigMapName: hdfs-znode
        listenerClass: external-unstable
        dfsReplication: 3
    nameNodes:
        roleGroups:
            default:
                replicas: 2
    dataNodes:
        roleGroups:
            default:
                replicas: 2
    journalNodes:
        roleGroups:
            default:
                replicas: 2
