apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
    name: kafka-connect-cluster
    annotations:
        strimzi.io/use-connector-resources: "true"
spec:
    version: 3.6.0
    replicas: 1
    bootstrapServers: "kafka-cluster-kafka-bootstrap:9093"
    #    tls:
    #        trustedCertificates:
    #            - secretName: kafka-cluster-cluster-ca-cert
    #              certificate: ca.crt
    config:
        group.id: kafka-connect-cluster
        offset.storage.topic: kafka-connect-cluster-offsets
        config.storage.topic: kafka-connect-cluster-configs
        status.storage.topic: kafka-connect-cluster-status
        key.converter: org.apache.kafka.connect.json.JsonConverter
        value.converter: org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable: true
        value.converter.schemas.enable: true
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1
