---
apiVersion: v1
kind: Service
metadata:
    name: kafka-schema-registry
spec:
    type: NodePort
    ports:
        - port: 8081
          targetPort: 8081
    selector:
        app: kafka-schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka-schema-registry
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-schema-registry
    template:
        metadata:
            labels:
                app: kafka-schema-registry
        spec:
            containers:
                - name: kafka-schema-registry
                  image: confluentinc/cp-schema-registry:7.3.1
                  env:
                      - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
                        value: "kafka-cluster-kafka-bootstrap:9092"
                      - name: SCHEMA_REGISTRY_HOST_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: SCHEMA_REGISTRY_LISTENERS
                        value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-connect
spec:
    type: NodePort
    ports:
        - port: 8083
          targetPort: 8083
    selector:
        app: kafka-connect
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kafka-connect-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka-connect
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-connect
    template:
        metadata:
            labels:
                app: kafka-connect
        spec:
            securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
            volumes:
                - name: kafka-connect-pv-storage
                  persistentVolumeClaim:
                      claimName: kafka-connect-pv-claim
            containers:
                - name: kafka-connect
                  image: cp-server-connect-base:latest
                  imagePullPolicy: "Never"
                  securityContext:
                      allowPrivilegeEscalation: false
                  volumeMounts:
                      - mountPath: "/data/"
                        name: kafka-connect-pv-storage
                  env:
                      - name: HADOOP_USER_NAME
                        value: "stackable"
                      - name: CONNECT_BOOTSTRAP_SERVERS
                        value: "kafka-cluster-kafka-bootstrap:9092"
                      - name: CONNECT_REST_PORT
                        value: "8083"
                      - name: CONNECT_REST_ADVERTISED_HOST_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: CONNECT_GROUP_ID
                        value: "kafka-connect-group-id-01"
                      - name: CONNECT_CONFIG_STORAGE_TOPIC
                        value: "_connect-configs"
                      - name: CONNECT_OFFSET_STORAGE_TOPIC
                        value: "_connect-offsets"
                      - name: CONNECT_STATUS_STORAGE_TOPIC
                        value: "_connect-status"
                      - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
                        value: "3"
                      - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
                        value: "3"
                      - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
                        value: "3"
                      - name: CONNECT_PLUGIN_PATH
                        value: "/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"
                      - name: CONNECT_KEY_CONVERTER
                        value: "io.confluent.connect.avro.AvroConverter"
                      - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
                        value: "http://kafka-schema-registry:8081"
                      - name: CONNECT_VALUE_CONVERTER
                        value: "io.confluent.connect.avro.AvroConverter"
                      - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
                        value: "http://kafka-schema-registry:8081"
                      - name: CONNECT_INTERNAL_KEY_CONVERTER
                        value: "org.apache.kafka.connect.json.JsonConverter"
                      - name: CONNECT_INTERNAL_VALUE_CONVERTER
                        value: "org.apache.kafka.connect.json.JsonConverter"
