---
apiVersion: v1
kind: Service
metadata:
    name: redpanda
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
    selector:
        app: redpanda
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redpanda
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redpanda
    template:
        metadata:
            labels:
                app: redpanda
        spec:
            containers:
                - name: redpanda
                  image: redpandadata/console:latest
                  env:
                      - name: KAFKA_BROKERS
                        value: "kafka-cluster-kafka-bootstrap:9092"
                      - name: KAFKA_SCHEMAREGISTRY_ENABLED
                        value: "true"
                      - name: KAFKA_SCHEMAREGISTRY_URLS
                        value: "http://kafka-schema-registry:8081"
#                      - name: CONNECT_ENABLED
#                        value: "true"
#                      - name: CONNECT_CLUSTERS_NAME
#                        value: "kafka-connect-cluster"
#                      - name: CONNECT_CLUSTERS_URL
#                        value: "http://kafka-connect:8083"
