name: Worker
on:
  push:
    branches:
      - main
      - dev
      - API's
    pull_request:
      branches:
        - main
        - dev

env:
  docker_username: spedsbjerg

jobs:
  TwitterAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: CurrentPath
        run: pwd
      - name: Directories
        run: ls
      - name: Install Dependencies
        #run: dotnet restore
        run: dotnet restore ./TwitterBotcoinAPI.sln
      - name: Build
        run: dotnet build
