name: Worker
on:
  push:
    branches:
      - main
      - dev
      - API's
    pull_request:
      branches:
        - main
        - dev

env:
  docker_username: spedsbjerg
  working-directory: ./TwitterBitcoinAPI

jobs:
  TwitterAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install Dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}
      - name: Build
        run: dotnet build
        working-directory: ${{env.working-directory}}
  
  DockerRunTwitterAPI:
    runs-on: ubuntu-latest
    needs: TwitterAPI
    steps:
      - uses: actions/checkout@v2

  StockMarketWebSocket:
    runs-on: ubuntu-latest

  DockerRunStockMarket:
    runs-on: ubuntu-latest
    needs: StockMarketWebSocket
  
  GoldMarketWebSocket:
    runs-on: ubuntu-latest

  DockerRunGoldMarket:
    runs-on: ubuntu-latest
    needs: GoldMarketWebSocket

  DockerCompose:
    runs-on: ubuntu-latest
    needs: [DockerRunTwitterAPI, DockerRunStockMarket, DockerRunGoldMarket]